seed: 42

device:
  device_type: gpu
  worker: cuda:0
  gpu_num_workers: 32

data:
  resolution: 256
  channel: 1

  classes:
    - death
    - alive

  source_dataset: claro_retrospettivo
  processed_dataset: claro_retrospettivo
  data_dir: ./data/data_raw
  interim_dir: ./data/interim
  reports_dir: ./reports/

  validation:
    name: bootstrap
    split:
      "train": 0.8
      "val": 0.1
      "test": 0.1
    n_exp: 5

  modes:
    CT:
      clip:
        min: -1000
        max: 1000
      scale:
        min: -1000
        max: 1000
      upper_percentile:
      lower_percentile:

  options:
    apply_box: True
    box_value: max_box # box
    transpose_img: False # Transpose the 2D slice swapping the axis, defaul True
    convert_to_uint8: False
    scale_by_255: True

network:
  model_name: 'stylegan2-ada'