seed: 42

device:
  device_type: cpu
  worker: cuda:0
  gpu_num_workers: 32

data:
  image_size: 256
  channel: 1

  source_dataset: Pelvis_2.1
  processed_dataset: Pelvis_2.1
  data_dir: ./data/data_raw
  interim_dir: ./data/interim
  reports_dir: ./reports/

  validation:
    name: hold_out
    split:
      "train": 0.7
      "val": 0.2
      "test": 0.1

  modes:
    MR_nonrigid_CT:
      range:
        min: -1000
        max: 1000
      upper_percentile:
      lower_percentile:

#    MR_MR_T2_BC:
#      range:
#        min: 0
#        max: 50
#      upper_percentile:
#      lower_percentile:

    MR_MR_T2:
      range:
        min: 0
        max: 3000
      upper_percentile:
      lower_percentile:

  preprocessing_option:
    process_dicom_2_nifti:
    process_nifti_resized:
    process_nifti_normalized:
    snap_pickle:
    snap_zip: on

network:
  model_name: 'stylegan2-ada'