seed: 42

device:
  device_type: cpu
  worker: cuda:0
  gpu_num_workers: 32

data:
  resolution: 256
  channel: 1

  classes: # name of classes
    - B
    - G
    - L
    - P
    - R

  source_dataset: Pelvis_2.1
  processed_dataset: Pelvis_2.1
  data_dir: ./data/data_raw
  interim_dir: ./data/interim
  reports_dir: ./reports/

  validation:
    name: hold_out
    split:
      "train": 0.7
      "val": 0.2
      "test": 0.1
    n_exp: 1

  modes:
    MR_nonrigid_CT:
      range:
        min: -1000
        max: 2000
      upper_percentile:
      lower_percentile:

#    MR_MR_T2_BC:
#      range:
#        min: 0
#        max: 50
#      upper_percentile:
#      lower_percentile:

    MR_MR_T2:
      range:
        min: 0
        max: 1900
      upper_percentile:
      lower_percentile:

  options:
    pop_range: 10 # Number of slice to drop and the beginning/end od the stack, default 10
    apply_mask: True # Apply to MR and CT the boolean mask computed using CT mode, default True
    transpose_img: True # Transpose the 2D slice swapping the axis, defaul True

network:
  model_name: 'stylegan2-ada'